I'm going back to Patrick's simple storage with brownie to review the basics of deployment ann initialisation

okaaay so I figured why when I try to run a script, it wasn't working.

1. I forgot the `export` at the beginning of my .env lines
2. I wasn't always in the right folder
3. I had to run `source .env`
4. I add to add `dotenv : .env` in my brownie-config.yaml

I fixed the issue of terminal error `Python-dotenv could not parse statement starting at line 1` (x4) by removing the "" around my .env values.

When I try to deploy

````def deploy_flashloan():
    account = accounts[0]
    print(account)```
ganache-cli gets stuck and does not return anything:

```brownie run scripts/deploy.py
Brownie v1.17.2 - Python development framework for Ethereum

UpdatedVersionProject is the active project.

Launching 'ganache-cli --port 8545 --gasLimit 12000000 --accounts 10 --hardfork istanbul --mnemonic brownie --fork https://mainnet.infura.io/v3/27f654aa13854abda9b50ac627cbda36 --chainId 1'..
```
````

I've added my own network by entering my private key (from metamask wallet used for tests), requested for my account's address to be printed to the terminal, and the result was only sucessful through using Kovan. ganache-cli keeps spinning and not resolving

===============
brownie run scripts/deploy.py --network kovan
Brownie v1.17.2 - Python development framework for Ethereum

UpdatedVersionProject is the active project.

Running 'scripts/deploy.py::main'...
Enter password for "flashloan-project":
0x4a8e4183709bb59E0807D64E46cFe7747479d371
===============

Deploying from .env private key also works, except for `Python-dotenv could not parse statement starting at line 2`, because I added "" around the hexadecimal variable that is my private key. Without double quotation marks, the message wsa `Error: Non-hexadecimal digit found`

I figured out what was going on. I imported the private key as a variable into brownie-config and got that into deploy.py.
This time, everything runs smooth:
===============
brownie run scripts/deploy.py --network kovan
Brownie v1.17.2 - Python development framework for Ethereum

UpdatedVersionProject is the active project.

Running 'scripts/deploy.py::main'...
0x4a8e4183709bb59E0807D64E46cFe7747479d371
anne@AnneSager:~/Documents/FlashArbitrage/Flashloan_Arbitrage/UPDATED_VERSION\$
===============

when trying to run the same script with deploying the smart contract, brownie returns this error

```
Brownie v1.17.2 - Python development framework for Ethereum

Compiling contracts...
  Solc version: 0.6.12
  Optimizer: Enabled  Runs: 200
  EVM Version: Istanbul
Generating build data...
 - OpenZeppelin/openzeppelin-contracts@3.0.0/Context
 - OpenZeppelin/openzeppelin-contracts@3.0.0/Ownable
 - OpenZeppelin/openzeppelin-contracts@3.0.0/SafeMath
 - OpenZeppelin/openzeppelin-contracts@3.0.0/ERC20
 - OpenZeppelin/openzeppelin-contracts@3.0.0/IERC20
 - OpenZeppelin/openzeppelin-contracts@3.0.0/SafeERC20
 - OpenZeppelin/openzeppelin-contracts@3.0.0/Address
 - Flashloan_logic
 - FlashLoanReceiverBaseV2
 - Withdrawable
 - IFlashLoanReceiverV2
 - ILendingPoolAddressesProviderV2
 - ILendingPoolV2
 - DataTypes

UpdatedVersionProject is the active project.

Running 'scripts/deploy.py::main'...
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/_cli/run.py", line 50, in main
    return_value, frame = run(
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy.py", line 5, in main
    deploy_flashloan()
  File "./scripts/deploy.py", line 11, in deploy_flashloan
    Flashloan_logic.deploy({"from": accountAnne})
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 528, in __call__
    return tx["from"].deploy(
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/account.py", line 509, in deploy
    data = contract.deploy.encode_input(*args)
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/network/contract.py", line 557, in encode_input
    data = format_input(self.abi, args)
  File "/usr/local/lib/python3.8/dist-packages/eth_brownie-1.17.2-py3.8.egg/brownie/convert/normalize.py", line 20, in format_input
    raise type(e)(f"{abi['name']} {e}") from None
ValueError: constructor Sequence has incorrect length, expected 1 but got 0
```
